# Config file for automatic testing at travis-ci.org
language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
install:
  - pip install tox
script: tox
services:
  - elasticsearch
  - mongodb
before_script:
  - sleep 10
  - travis_retry curl -XDELETE 'http://localhost:9200/nefertari_starter/'
  - mongo nefertari_starter --eval 'db.dropDatabase();'
