# Config file for automatic testing at travis-ci.org
language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install:
  - pip install tox
script: tox
services:
  - mongodb
  - elasticsearch
before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb
before_script:
  - sleep 15
  - curl -XDELETE 'http://localhost:9200/nefertari_scaffold/'
  - mongo nefertari_scaffold --eval 'db.dropDatabase();'
