# Config file for automatic testing at travis-ci.org
language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install:
  - pip install tox
script: tox
services:
  - mongodb
before_install:
  - travis_retry curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew --force-confdef elasticsearch-1.7.5.deb
  - sudo service elasticsearch start
  - sleep 10
before_script:
  - sleep 30
  - travis_retry curl -XDELETE 'http://localhost:9200/nefertari_starter/'
  - mongo nefertari_starter --eval 'db.dropDatabase();'
